export const mockRisks = [
  {
    id: 1,
    title: "Unencrypted user data in transit",
    category: "Security",
    status: "Open",
    priority: "High",
    score: 85,
    owner: "Alice Johnson",
    createdDate: "2026-04-01",
  },
  {
    id: 2,
    title: "AI model hallucination in reports",
    category: "AI Risk",
    status: "In Progress",
    priority: "Medium",
    score: 62,
    owner: "Bob Smith",
    createdDate: "2026-04-05",
  },
  {
    id: 3,
    title: "No audit log for admin actions",
    category: "Compliance",
    status: "Open",
    priority: "High",
    score: 78,
    owner: "Carol White",
    createdDate: "2026-04-08",
  },
  {
    id: 4,
    title: "Third-party API has no SLA",
    category: "Operational",
    status: "Resolved",
    priority: "Low",
    score: 30,
    owner: "David Lee",
    createdDate: "2026-04-10",
  },
  {
    id: 5,
    title: "Missing input validation on forms",
    category: "Security",
    status: "In Progress",
    priority: "Medium",
    score: 55,
    owner: "Eva Green",
    createdDate: "2026-04-12",
  },
];